platform :ios, '8.1'
pod 'AFNetworking', '~> 2.6'
pod 'SDWebImage', '~>3.7'
pod 'ObjectiveRecord', '~>1.5'
pod 'GBInfiniteScrollView', '~> 1.6'
pod 'VENTokenField', '~> 2.4'
pod 'ActionSheetPicker-3.0', '~> 2.0.1'