platform :ios, '8.1'
pod 'AFNetworking', '~> 2.5.4'
pod 'SDWebImage', '~>3.7'
pod 'ObjectiveRecord', '~>1.5'
pod 'HockeySDK', '~>3.6.2'
pod 'GBInfiniteScrollView', '~> 1.6'
pod 'VENTokenField', '~> 2.0'
pod 'ActionSheetPicker-3.0', '~> 1.5.1'